version: '3.4'


x-server-base: &x-server-base
    image: dive/server:lastest
    build:
        context: ./dive-backend/
        dockerfile: Dockerfile
    volumes:
        - ./dive-backend/:/usr/src/app/
    depends_on:
        - rabbit
        - db


services:

    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass

    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=divedb_user
            - POSTGRES_PASSWORD=divedb_pass
            - POSTGRES_DB=divedb_prod

    dive-worker:
        <<: *x-server-base
        command: celery -A dive.worker.core worker --loglevel INFO

    dive-api:
        <<: *x-server-base
        command: bash -c 'python run_server.py'
        # command: bash -c "
        #     gunicorn
        #         --config dive/server/gunicorn-config.py
        #         --pythonpath server dive.server.core:app
        #         --log-level INFO
        #         --reload"
        ports:
            - 8081:8081

    dive-frontend:
        image: node:7
        environment:
            - API_URL=http://localhost:8081/api
            - DEBUG=true
            - NODE_ENV=DEVELOPMENT
        working_dir: /app/
        command: bash -c 'npm install && npm start'
        volumes:
            - ./dive-frontend/:/app/
        ports:
            - 3009:3009

volumes:
    postgres_data:
